# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
