# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0003_conference_division_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='strength',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
