# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0006_auto_20161211_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Series'),
        ),
    ]
