# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0007_auto_20161211_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='current_day',
            field=models.IntegerField(null=True),
        ),
    ]
