# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0008_schedule_current_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='home_advantage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_loser', to='ncl_app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='ncl_app.Team'),
        ),
        migrations.AlterField(
            model_name='series',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_loser', to='ncl_app.Team'),
        ),
        migrations.AlterField(
            model_name='series',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_winner', to='ncl_app.Team'),
        ),
    ]
