# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0009_auto_20161213_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='current_day',
        ),
    ]
