# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0010_remove_schedule_current_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='current_day',
            field=models.IntegerField(default=0),
        ),
    ]
