# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0012_team_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=10)),
                ('outcome', models.CharField(choices=[('X', 'draw'), ('1', 'home'), ('2', 'away')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Result'),
        ),
        migrations.AddField(
            model_name='matchpart',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Match'),
        ),
        migrations.AddField(
            model_name='matchpart',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(through='ncl_app.MatchPart', to='ncl_app.Team'),
        ),
    ]
