# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0013_auto_20161215_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='division',
        ),
        migrations.AddField(
            model_name='division',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Schedule'),
        ),
    ]
