# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0014_auto_20161219_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={},
        ),
        migrations.RemoveField(
            model_name='division',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Division'),
        ),
    ]
