# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0015_auto_20161219_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Division'),
        ),
    ]
