# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0016_auto_20161219_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='division',
        ),
        migrations.AddField(
            model_name='division',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Schedule'),
        ),
    ]
