# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0017_auto_20161219_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncl_app.Schedule'),
        ),
    ]
