# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0018_auto_20161219_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.AddField(
            model_name='match',
            name='outcome',
            field=models.CharField(choices=[('X', 'draw'), ('1', 'home'), ('2', 'away')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default='0-0', max_length=10),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
