# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_app', '0020_auto_20161219_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='postseason',
            field=models.BooleanField(default=False),
        ),
    ]
